syntax = "proto3";

package routing;

// GCS output protos for preprocessing stages.

message ShardGraph {
    repeated Edge edges = 1;
    repeated NodeLocation locations = 2;
    repeated fixed64 boundary_in_node_ids = 3 [packed = true];
    repeated fixed64 boundary_out_node_ids = 4 [packed = true];
}

// Unused, kept for debugging
message Shortcuts {
    repeated Edge edges = 1;
}

message Edge {
    fixed64 from_node_id = 1;
    fixed64 to_node_id = 2;
    uint32 weight = 3;
    bool bidirectional = 4;
}

message NodeLocation {
    fixed64 node_id = 1;
    double x = 2; // lng
    double y = 3; // lat
}

message OverlayGraph {
    // Bridges (connecting different shards)
    repeated Edge bridges = 1;

    // Shortcuts (connecting two boundary nodes in the same shard)
    repeated Edge shortcuts = 2;

    // Boundary node locations for rendering.
    repeated NodeLocation boundary_locations = 3;
}