# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bigtable_storage.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62igtable_storage.proto\x12\x07routing\"T\n\nShardGraph\x12\x1c\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\r.routing.Edge\x12(\n\tlocations\x18\x02 \x03(\x0b\x32\x15.routing.NodeLocation\")\n\tShortcuts\x12\x1c\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\r.routing.Edge\"W\n\x04\x45\x64ge\x12\x14\n\x0c\x66rom_node_id\x18\x01 \x01(\x06\x12\x12\n\nto_node_id\x18\x02 \x01(\x06\x12\x0e\n\x06weight\x18\x03 \x01(\r\x12\x15\n\rbidirectional\x18\x04 \x01(\x08\"5\n\x0cNodeLocation\x12\x0f\n\x07node_id\x18\x01 \x01(\x06\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"\x83\x01\n\x0cOverlayGraph\x12\x1e\n\x07\x62ridges\x18\x01 \x03(\x0b\x32\r.routing.Edge\x12 \n\tshortcuts\x18\x02 \x03(\x0b\x32\r.routing.Edge\x12\x31\n\x12\x62oundary_locations\x18\x03 \x03(\x0b\x32\x15.routing.NodeLocationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bigtable_storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHARDGRAPH']._serialized_start=35
  _globals['_SHARDGRAPH']._serialized_end=119
  _globals['_SHORTCUTS']._serialized_start=121
  _globals['_SHORTCUTS']._serialized_end=162
  _globals['_EDGE']._serialized_start=164
  _globals['_EDGE']._serialized_end=251
  _globals['_NODELOCATION']._serialized_start=253
  _globals['_NODELOCATION']._serialized_end=306
  _globals['_OVERLAYGRAPH']._serialized_start=309
  _globals['_OVERLAYGRAPH']._serialized_end=440
# @@protoc_insertion_point(module_scope)
