// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v3.19.1
// source: bigtable_storage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "routing";

/**
 * BIGTABLE TABLE: shards
 * ROW KEY: "S#" + s2_cell_id
 */
export interface ShardGraph {
  edges: Edge[];
  locations: NodeLocation[];
}

export interface Edge {
  fromNodeId: number;
  toNodeId: number;
  weight: number;
  bidirectional: boolean;
}

export interface NodeLocation {
  nodeId: number;
  x: number;
  y: number;
}

/**
 * BIGTABLE TABLE: shortcuts
 * ROW KEY: "P#" + from_node_id + "#" + to_node_id
 */
export interface ShortcutPath {
  nodes: number[];
}

/**
 * BIGTABLE TABLE: node_index
 * ROW KEY: "N#" + node_id (string)
 */
export interface ShardLookup {
  shardId: number;
}

/** Stored in ?, every worker loads it on startup */
export interface OverlayGraph {
  /** Bridges (connecting different shards) */
  bridges: Edge[];
  /** Shortcuts (connecting two nodes in the same shard) */
  shortcuts: Edge[];
}

function createBaseShardGraph(): ShardGraph {
  return { edges: [], locations: [] };
}

export const ShardGraph: MessageFns<ShardGraph> = {
  encode(message: ShardGraph, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.edges) {
      Edge.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.locations) {
      NodeLocation.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ShardGraph {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseShardGraph();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.edges.push(Edge.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.locations.push(NodeLocation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ShardGraph {
    return {
      edges: globalThis.Array.isArray(object?.edges) ? object.edges.map((e: any) => Edge.fromJSON(e)) : [],
      locations: globalThis.Array.isArray(object?.locations)
        ? object.locations.map((e: any) => NodeLocation.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ShardGraph): unknown {
    const obj: any = {};
    if (message.edges?.length) {
      obj.edges = message.edges.map((e) => Edge.toJSON(e));
    }
    if (message.locations?.length) {
      obj.locations = message.locations.map((e) => NodeLocation.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ShardGraph>, I>>(base?: I): ShardGraph {
    return ShardGraph.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ShardGraph>, I>>(object: I): ShardGraph {
    const message = createBaseShardGraph();
    message.edges = object.edges?.map((e) => Edge.fromPartial(e)) || [];
    message.locations = object.locations?.map((e) => NodeLocation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEdge(): Edge {
  return { fromNodeId: 0, toNodeId: 0, weight: 0, bidirectional: false };
}

export const Edge: MessageFns<Edge> = {
  encode(message: Edge, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fromNodeId !== 0) {
      writer.uint32(9).fixed64(message.fromNodeId);
    }
    if (message.toNodeId !== 0) {
      writer.uint32(17).fixed64(message.toNodeId);
    }
    if (message.weight !== 0) {
      writer.uint32(24).uint32(message.weight);
    }
    if (message.bidirectional !== false) {
      writer.uint32(32).bool(message.bidirectional);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Edge {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEdge();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.fromNodeId = longToNumber(reader.fixed64());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.toNodeId = longToNumber(reader.fixed64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.weight = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.bidirectional = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Edge {
    return {
      fromNodeId: isSet(object.fromNodeId)
        ? globalThis.Number(object.fromNodeId)
        : isSet(object.from_node_id)
        ? globalThis.Number(object.from_node_id)
        : 0,
      toNodeId: isSet(object.toNodeId)
        ? globalThis.Number(object.toNodeId)
        : isSet(object.to_node_id)
        ? globalThis.Number(object.to_node_id)
        : 0,
      weight: isSet(object.weight) ? globalThis.Number(object.weight) : 0,
      bidirectional: isSet(object.bidirectional) ? globalThis.Boolean(object.bidirectional) : false,
    };
  },

  toJSON(message: Edge): unknown {
    const obj: any = {};
    if (message.fromNodeId !== 0) {
      obj.fromNodeId = Math.round(message.fromNodeId);
    }
    if (message.toNodeId !== 0) {
      obj.toNodeId = Math.round(message.toNodeId);
    }
    if (message.weight !== 0) {
      obj.weight = Math.round(message.weight);
    }
    if (message.bidirectional !== false) {
      obj.bidirectional = message.bidirectional;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Edge>, I>>(base?: I): Edge {
    return Edge.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Edge>, I>>(object: I): Edge {
    const message = createBaseEdge();
    message.fromNodeId = object.fromNodeId ?? 0;
    message.toNodeId = object.toNodeId ?? 0;
    message.weight = object.weight ?? 0;
    message.bidirectional = object.bidirectional ?? false;
    return message;
  },
};

function createBaseNodeLocation(): NodeLocation {
  return { nodeId: 0, x: 0, y: 0 };
}

export const NodeLocation: MessageFns<NodeLocation> = {
  encode(message: NodeLocation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== 0) {
      writer.uint32(9).fixed64(message.nodeId);
    }
    if (message.x !== 0) {
      writer.uint32(21).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(29).float(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NodeLocation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeLocation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.nodeId = longToNumber(reader.fixed64());
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.y = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeLocation {
    return {
      nodeId: isSet(object.nodeId)
        ? globalThis.Number(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.Number(object.node_id)
        : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: NodeLocation): unknown {
    const obj: any = {};
    if (message.nodeId !== 0) {
      obj.nodeId = Math.round(message.nodeId);
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeLocation>, I>>(base?: I): NodeLocation {
    return NodeLocation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeLocation>, I>>(object: I): NodeLocation {
    const message = createBaseNodeLocation();
    message.nodeId = object.nodeId ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseShortcutPath(): ShortcutPath {
  return { nodes: [] };
}

export const ShortcutPath: MessageFns<ShortcutPath> = {
  encode(message: ShortcutPath, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.nodes) {
      writer.fixed64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ShortcutPath {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseShortcutPath();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 9) {
            message.nodes.push(longToNumber(reader.fixed64()));

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.nodes.push(longToNumber(reader.fixed64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ShortcutPath {
    return { nodes: globalThis.Array.isArray(object?.nodes) ? object.nodes.map((e: any) => globalThis.Number(e)) : [] };
  },

  toJSON(message: ShortcutPath): unknown {
    const obj: any = {};
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ShortcutPath>, I>>(base?: I): ShortcutPath {
    return ShortcutPath.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ShortcutPath>, I>>(object: I): ShortcutPath {
    const message = createBaseShortcutPath();
    message.nodes = object.nodes?.map((e) => e) || [];
    return message;
  },
};

function createBaseShardLookup(): ShardLookup {
  return { shardId: 0 };
}

export const ShardLookup: MessageFns<ShardLookup> = {
  encode(message: ShardLookup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shardId !== 0) {
      writer.uint32(9).fixed64(message.shardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ShardLookup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseShardLookup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.shardId = longToNumber(reader.fixed64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ShardLookup {
    return {
      shardId: isSet(object.shardId)
        ? globalThis.Number(object.shardId)
        : isSet(object.shard_id)
        ? globalThis.Number(object.shard_id)
        : 0,
    };
  },

  toJSON(message: ShardLookup): unknown {
    const obj: any = {};
    if (message.shardId !== 0) {
      obj.shardId = Math.round(message.shardId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ShardLookup>, I>>(base?: I): ShardLookup {
    return ShardLookup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ShardLookup>, I>>(object: I): ShardLookup {
    const message = createBaseShardLookup();
    message.shardId = object.shardId ?? 0;
    return message;
  },
};

function createBaseOverlayGraph(): OverlayGraph {
  return { bridges: [], shortcuts: [] };
}

export const OverlayGraph: MessageFns<OverlayGraph> = {
  encode(message: OverlayGraph, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.bridges) {
      Edge.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.shortcuts) {
      Edge.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OverlayGraph {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOverlayGraph();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bridges.push(Edge.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.shortcuts.push(Edge.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OverlayGraph {
    return {
      bridges: globalThis.Array.isArray(object?.bridges) ? object.bridges.map((e: any) => Edge.fromJSON(e)) : [],
      shortcuts: globalThis.Array.isArray(object?.shortcuts) ? object.shortcuts.map((e: any) => Edge.fromJSON(e)) : [],
    };
  },

  toJSON(message: OverlayGraph): unknown {
    const obj: any = {};
    if (message.bridges?.length) {
      obj.bridges = message.bridges.map((e) => Edge.toJSON(e));
    }
    if (message.shortcuts?.length) {
      obj.shortcuts = message.shortcuts.map((e) => Edge.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OverlayGraph>, I>>(base?: I): OverlayGraph {
    return OverlayGraph.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OverlayGraph>, I>>(object: I): OverlayGraph {
    const message = createBaseOverlayGraph();
    message.bridges = object.bridges?.map((e) => Edge.fromPartial(e)) || [];
    message.shortcuts = object.shortcuts?.map((e) => Edge.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
