[project]
name = "scripts"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "google-cloud-storage>=2.18.0",
    "grpcio==1.64.1",
    "grpcio-tools==1.64.1",
    "igraph",
    "osmium>=4.0.0",
    "pyarrow>=17.0.0",
    "protobuf==5.26.1",
]

[tool.uv]
package = false
