# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcs_storage.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gcs_storage.proto\x12\x07routing\"\x99\x01\n\nShardGraph\x12\x1c\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\r.routing.Edge\x12(\n\tlocations\x18\x02 \x03(\x0b\x32\x15.routing.NodeLocation\x12 \n\x14\x62oundary_in_node_ids\x18\x03 \x03(\x06\x42\x02\x10\x01\x12!\n\x15\x62oundary_out_node_ids\x18\x04 \x03(\x06\x42\x02\x10\x01\")\n\tShortcuts\x12\x1c\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\r.routing.Edge\"W\n\x04\x45\x64ge\x12\x14\n\x0c\x66rom_node_id\x18\x01 \x01(\x06\x12\x12\n\nto_node_id\x18\x02 \x01(\x06\x12\x0e\n\x06weight\x18\x03 \x01(\r\x12\x15\n\rbidirectional\x18\x04 \x01(\x08\"5\n\x0cNodeLocation\x12\x0f\n\x07node_id\x18\x01 \x01(\x06\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"\x83\x01\n\x0cOverlayGraph\x12\x1e\n\x07\x62ridges\x18\x01 \x03(\x0b\x32\r.routing.Edge\x12 \n\tshortcuts\x18\x02 \x03(\x0b\x32\r.routing.Edge\x12\x31\n\x12\x62oundary_locations\x18\x03 \x03(\x0b\x32\x15.routing.NodeLocationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gcs_storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHARDGRAPH'].fields_by_name['boundary_in_node_ids']._loaded_options = None
  _globals['_SHARDGRAPH'].fields_by_name['boundary_in_node_ids']._serialized_options = b'\020\001'
  _globals['_SHARDGRAPH'].fields_by_name['boundary_out_node_ids']._loaded_options = None
  _globals['_SHARDGRAPH'].fields_by_name['boundary_out_node_ids']._serialized_options = b'\020\001'
  _globals['_SHARDGRAPH']._serialized_start=31
  _globals['_SHARDGRAPH']._serialized_end=184
  _globals['_SHORTCUTS']._serialized_start=186
  _globals['_SHORTCUTS']._serialized_end=227
  _globals['_EDGE']._serialized_start=229
  _globals['_EDGE']._serialized_end=316
  _globals['_NODELOCATION']._serialized_start=318
  _globals['_NODELOCATION']._serialized_end=371
  _globals['_OVERLAYGRAPH']._serialized_start=374
  _globals['_OVERLAYGRAPH']._serialized_end=505
# @@protoc_insertion_point(module_scope)

