syntax = "proto3";

package routing;

// TODO - right now both graphs are designed for minimal duplication
// but we can try to duplicate some data in the OverlayGraph to 
// make it faster to load

// ----------------------------------------------------------------------------------------


// BIGTABLE TABLE: shards
// ROW KEY: "S#" + s2_cell_id
message ShardGraph {
    repeated Edge edges = 1;
    repeated NodeLocation locations = 2;
}

message Edge {
    fixed64 from_node_id = 1;
    fixed64 to_node_id = 2;
    uint32 weight = 3;
    bool bidirectional = 4;
}

message NodeLocation {
    fixed64 node_id = 1;
    float x = 2;
    float y = 3;
}


// BIGTABLE TABLE: shortcuts
// ROW KEY: "P#" + from_node_id + "#" + to_node_id
message ShortcutPath {
    repeated fixed64 nodes = 1 [packed = true];
}


// BIGTABLE TABLE: node_index
// ROW KEY: "N#" + node_id (string)
message ShardLookup {
    fixed64 shard_id = 1;
}

// BIGTABLE TABLE: overlay_graph
// ROW KEY: "O#"
// Single row with all the data.
message OverlayGraph {
    // Bridges (connecting different shards) 
    repeated Edge bridges = 1;

    // Shortcuts (connecting two nodes in the same shard)
    repeated Edge shortcuts = 2;
}
