# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serving_layer/bigtable_storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serving_layer/bigtable_storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$serving_layer/bigtable_storage.proto\x12\x07routing\"T\n\nShardGraph\x12\x1c\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\r.routing.Edge\x12(\n\tlocations\x18\x02 \x03(\x0b\x32\x15.routing.NodeLocation\"i\n\x04\x45\x64ge\x12\x14\n\x0c\x66rom_node_id\x18\x01 \x01(\x06\x12\x12\n\nto_node_id\x18\x02 \x01(\x06\x12\x0e\n\x06weight\x18\x03 \x01(\r\x12\x15\n\rbidirectional\x18\x04 \x01(\x08\x12\x10\n\x04path\x18\x05 \x03(\x06\x42\x02\x10\x01\"5\n\x0cNodeLocation\x12\x0f\n\x07node_id\x18\x01 \x01(\x06\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"!\n\x0cShortcutPath\x12\x11\n\x05nodes\x18\x01 \x03(\x06\x42\x02\x10\x01\"\x1f\n\x0bShardLookup\x12\x10\n\x08shard_id\x18\x01 \x01(\x06\"P\n\x0cOverlayGraph\x12\x1e\n\x07\x62ridges\x18\x01 \x03(\x0b\x32\r.routing.Edge\x12 \n\tshortcuts\x18\x02 \x03(\x0b\x32\r.routing.Edgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serving_layer.bigtable_storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDGE'].fields_by_name['path']._loaded_options = None
  _globals['_EDGE'].fields_by_name['path']._serialized_options = b'\020\001'
  _globals['_SHORTCUTPATH'].fields_by_name['nodes']._loaded_options = None
  _globals['_SHORTCUTPATH'].fields_by_name['nodes']._serialized_options = b'\020\001'
  _globals['_SHARDGRAPH']._serialized_start=49
  _globals['_SHARDGRAPH']._serialized_end=133
  _globals['_EDGE']._serialized_start=135
  _globals['_EDGE']._serialized_end=240
  _globals['_NODELOCATION']._serialized_start=242
  _globals['_NODELOCATION']._serialized_end=295
  _globals['_SHORTCUTPATH']._serialized_start=297
  _globals['_SHORTCUTPATH']._serialized_end=330
  _globals['_SHARDLOOKUP']._serialized_start=332
  _globals['_SHARDLOOKUP']._serialized_end=363
  _globals['_OVERLAYGRAPH']._serialized_start=365
  _globals['_OVERLAYGRAPH']._serialized_end=445
# @@protoc_insertion_point(module_scope)
