# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shard_worker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shard_worker.proto\x12\x07routing\"&\n\nCoordinate\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lng\x18\x02 \x01(\x01\"4\n\x07NodeRef\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\"n\n\x1bSnapAndBoundaryDistsRequest\x12\x10\n\x08shard_id\x18\x01 \x01(\x04\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\x12#\n\x04mode\x18\x04 \x01(\x0e\x32\x15.routing.BoundaryMode\"\xe6\x01\n\x1cSnapAndBoundaryDistsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12!\n\x07snapped\x18\x03 \x01(\x0b\x32\x10.routing.NodeRef\x12\x19\n\x11\x62oundary_node_ids\x18\x04 \x03(\x04\x12?\n\x05\x64ists\x18\x05 \x03(\x0b\x32\x30.routing.SnapAndBoundaryDistsResponse.DistsEntry\x1a,\n\nDistsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"K\n\x11\x45xpandPathRequest\x12\x10\n\x08shard_id\x18\x01 \x01(\x04\x12\x11\n\tu_node_id\x18\x02 \x01(\x04\x12\x11\n\tv_node_id\x18\x03 \x01(\x04\"l\n\x12\x45xpandPathResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12%\n\x08polyline\x18\x03 \x03(\x0b\x32\x13.routing.Coordinate\x12\x14\n\x0ctotal_weight\x18\x04 \x01(\r\"\x0f\n\rHealthRequest\"\x1c\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08*1\n\x0c\x42oundaryMode\x12\x10\n\x0c\x42OUNDARY_OUT\x10\x00\x12\x0f\n\x0b\x42OUNDARY_IN\x10\x01\x32\xf4\x01\n\x0bShardWorker\x12\x63\n\x14SnapAndBoundaryDists\x12$.routing.SnapAndBoundaryDistsRequest\x1a%.routing.SnapAndBoundaryDistsResponse\x12\x45\n\nExpandPath\x12\x1a.routing.ExpandPathRequest\x1a\x1b.routing.ExpandPathResponse\x12\x39\n\x06Health\x12\x16.routing.HealthRequest\x1a\x17.routing.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shard_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNAPANDBOUNDARYDISTSRESPONSE_DISTSENTRY']._loaded_options = None
  _globals['_SNAPANDBOUNDARYDISTSRESPONSE_DISTSENTRY']._serialized_options = b'8\001'
  _globals['_BOUNDARYMODE']._serialized_start=704
  _globals['_BOUNDARYMODE']._serialized_end=753
  _globals['_COORDINATE']._serialized_start=31
  _globals['_COORDINATE']._serialized_end=69
  _globals['_NODEREF']._serialized_start=71
  _globals['_NODEREF']._serialized_end=123
  _globals['_SNAPANDBOUNDARYDISTSREQUEST']._serialized_start=125
  _globals['_SNAPANDBOUNDARYDISTSREQUEST']._serialized_end=235
  _globals['_SNAPANDBOUNDARYDISTSRESPONSE']._serialized_start=238
  _globals['_SNAPANDBOUNDARYDISTSRESPONSE']._serialized_end=468
  _globals['_SNAPANDBOUNDARYDISTSRESPONSE_DISTSENTRY']._serialized_start=424
  _globals['_SNAPANDBOUNDARYDISTSRESPONSE_DISTSENTRY']._serialized_end=468
  _globals['_EXPANDPATHREQUEST']._serialized_start=470
  _globals['_EXPANDPATHREQUEST']._serialized_end=545
  _globals['_EXPANDPATHRESPONSE']._serialized_start=547
  _globals['_EXPANDPATHRESPONSE']._serialized_end=655
  _globals['_HEALTHREQUEST']._serialized_start=657
  _globals['_HEALTHREQUEST']._serialized_end=672
  _globals['_HEALTHRESPONSE']._serialized_start=674
  _globals['_HEALTHRESPONSE']._serialized_end=702
  _globals['_SHARDWORKER']._serialized_start=756
  _globals['_SHARDWORKER']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
