# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shard_worker_pb2 as shard__worker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shard_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SnapAndBoundaryDists = channel.unary_unary(
                '/routing.ShardWorker/SnapAndBoundaryDists',
                request_serializer=shard__worker__pb2.SnapAndBoundaryDistsRequest.SerializeToString,
                response_deserializer=shard__worker__pb2.SnapAndBoundaryDistsResponse.FromString,
                _registered_method=True)
        self.ExpandPath = channel.unary_unary(
                '/routing.ShardWorker/ExpandPath',
                request_serializer=shard__worker__pb2.ExpandPathRequest.SerializeToString,
                response_deserializer=shard__worker__pb2.ExpandPathResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/routing.ShardWorker/Health',
                request_serializer=shard__worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=shard__worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class ShardWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SnapAndBoundaryDists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SnapAndBoundaryDists': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapAndBoundaryDists,
                    request_deserializer=shard__worker__pb2.SnapAndBoundaryDistsRequest.FromString,
                    response_serializer=shard__worker__pb2.SnapAndBoundaryDistsResponse.SerializeToString,
            ),
            'ExpandPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandPath,
                    request_deserializer=shard__worker__pb2.ExpandPathRequest.FromString,
                    response_serializer=shard__worker__pb2.ExpandPathResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shard__worker__pb2.HealthRequest.FromString,
                    response_serializer=shard__worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routing.ShardWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('routing.ShardWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SnapAndBoundaryDists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routing.ShardWorker/SnapAndBoundaryDists',
            shard__worker__pb2.SnapAndBoundaryDistsRequest.SerializeToString,
            shard__worker__pb2.SnapAndBoundaryDistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpandPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routing.ShardWorker/ExpandPath',
            shard__worker__pb2.ExpandPathRequest.SerializeToString,
            shard__worker__pb2.ExpandPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routing.ShardWorker/Health',
            shard__worker__pb2.HealthRequest.SerializeToString,
            shard__worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
